apiVersion: apps/v1
kind: Deployment
metadata:
  name: speeddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speed
      version: "1.0"
  strategy:
    type: RollingUpdate
      RollingUpdate:
        MaxSurge: 1
        MaxUnavalible: 0

  selector: 
    matchLabels:
      app: speed
      version: "1.0"
  template:
    metadata:
      labels:
        app: speed
        version: "1.0"
    spec:
      containers:
        - name: speedcontainer
          image: veeranjaneyulupagant/speed:1.0
          ports:
            - name: tomcatport
              containerPort: 8080
              protocal: TCP
          readinessProbe:
            httpGet:
              path: /speed/health/readiness.htm
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /speed/health/liveness.htm
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1024Mi
              
              
          
          